pipeline {
    agent any

    environment {
        DOCKER_IMAGE   = "pavan2045/alumni-portal-app"
        KUBE_NAMESPACE = "default"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Pavan20045/Alumni_Connect_Plus.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('catastrophe') {
                    script {
                        docker.build("${DOCKER_IMAGE}:latest")
                    }
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        docker.image("${DOCKER_IMAGE}:latest").push('latest')
                    }
                }
            }
        }

        stage('Deploy to Kubernetes (Minikube)') {
            steps {
                dir('catastrophe') {
                    bat """
                    kubectl apply -f k8s/
                    kubectl rollout restart deployment alumni-portal-deployment -n default
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI/CD PIPELINE COMPLETED SUCCESSFULLY"
        }
        failure {
            echo "❌ CI/CD PIPELINE FAILED"
        }
    }
}
