pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "pavan2045/alumni-portal-app"
        KUBE_NAMESPACE = "default"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/Pavan20045/Alumni_Connect_Plus.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Push Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        docker.image("${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }

        stage('Deploy to Kubernetes (Minikube)') {
            steps {
                bat """
                kubectl apply -f k8s/
                kubectl rollout restart deployment alumni-portal-deployment
                """
            }
        }
    }
}
